### ISSUE TITLE
Austria ntv2 grid

### ISSUE THREAD

**Issue by sfloery** [NaturalGIS/ntv2_transformations#9] opened 2015-08-27 13:24 UTC
Here is a link to the austrian ntv2 grid: 
http://www.bev.gv.at/portal/page?_pageid=713,2103845&_dad=portal&_schema=PORTAL

**Comment by gioman** [comment] 2015-08-27 16:29
Hi, is the ntv2 grid freely reditributable? any license? what are the EPSG codes of the CRSs supported by ths grid? can you provide data (or link to) to test the transformation? Thanks!

**Comment by gioman** [comment] 2015-10-01 20:19
duplicate of https://github.com/NaturalGIS/ntv2_transformations/issues/10

**Closed by gioman** 2015-10-01 20:19 UTC
Labels: enhancement
